# Generated by Django 2.2 on 2019-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190314_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ctps',
            field=models.CharField(default=123456, max_length=20, verbose_name='Carteira de Trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='serie',
            field=models.CharField(default=654321, max_length=10, verbose_name='Série'),
            preserve_default=False,
        ),
    ]
