# Generated by Django 2.2 on 2019-04-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='historico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='financeiro.Historico'),
        ),
        migrations.AlterField(
            model_name='pagamentopago',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_pagamento_pago', to='financeiro.ContaPagar'),
        ),
    ]
