# Generated by Django 2.2 on 2019-04-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20190408_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'ordering': ('-data_vencimento', 'valor_vendido')},
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='valor',
            new_name='valor_vendido',
        ),
    ]
