# Generated by Django 2.2 on 2019-04-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20190406_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentorecebido',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentorecebido', to='financeiro.ContaReceber'),
        ),
    ]
