# Generated by Django 2.1.3 on 2019-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='deadline',
            field=models.DateField(default='2019-02-03', verbose_name='Próximo Parecer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='created_on',
            field=models.DateField(auto_now=True, verbose_name='Criado em.'),
        ),
    ]
