# Generated by Django 2.1.3 on 2019-03-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20190320_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviar para'),
            preserve_default=False,
        ),
    ]
