# Generated by Django 2.1.3 on 2019-03-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_atendimento_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parecer',
            name='atendimento',
        ),
        migrations.DeleteModel(
            name='Parecer',
        ),
    ]
