# Generated by Django 2.1.3 on 2019-03-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190321_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produtos', to='core.SalesItem', verbose_name='Produto'),
        ),
    ]
