# Generated by Django 2.1.3 on 2019-03-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190322_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produtos', to='core.SalesItem', verbose_name='Produto'),
        ),
    ]
