# Generated by Django 2.1.3 on 2019-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_atendimento_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Encerrado'),
        ),
    ]
