# Generated by Django 2.2 on 2019-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_atendimento_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Encerrado?'),
        ),
    ]
