# Generated by Django 2.2 on 2019-04-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190403_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='department',
            field=models.CharField(choices=[('0', 'Folha'), ('1', 'Contábil'), ('2', 'Fiscal'), ('3', 'Financeiro')], default='0', max_length=15, verbose_name='Departamento'),
        ),
    ]
