# Generated by Django 2.2 on 2019-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_atendimento_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='department',
            field=models.CharField(choices=[('0', 'Folha'), ('1', 'Contábil'), ('2', 'Fiscal'), ('3', 'Financeiro')], default='3', max_length=15, verbose_name='Departamento'),
        ),
    ]
