# Generated by Django 2.2 on 2019-04-16 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_auto_20190409_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofservice',
            name='user_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário destino CRM'),
            preserve_default=False,
        ),
    ]
