# Generated by Django 2.2 on 2019-11-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_typeofservice_user_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produtos', to='core.Product', verbose_name='Produto'),
        ),
    ]
