# Generated by Django 2.1.3 on 2019-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190315_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_representative',
            field=models.BooleanField(default=False, verbose_name='É representante?'),
        ),
    ]
