# Generated by Django 2.1.3 on 2019-03-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_item', to='core.SalesItem', verbose_name='Produto')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_sale_item', to='core.SalesItem', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Venda Detalhe',
                'verbose_name_plural': 'Vendas Detalhe',
            },
        ),
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='client',
        ),
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Sales', verbose_name='Cliente'),
        ),
    ]
