# Generated by Django 2.1.3 on 2019-03-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190322_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_item', to='core.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_sale_item', to='core.Sales', verbose_name='Venda'),
        ),
    ]
