# Generated by Django 2.1.3 on 2019-03-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190322_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_sale', to='core.Client', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
