# Generated by Django 2.1.3 on 2019-03-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190322_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='products',
        ),
    ]
