# Generated by Django 2.2 on 2019-11-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_client_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
