# Generated by Django 2.2 on 2019-11-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191122_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_item', to='core.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Preço'),
        ),
    ]
