# Generated by Django 2.2 on 2020-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200331_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Preço'),
        ),
    ]
