# Generated by Django 2.2 on 2020-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200329_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Quantidade'),
        ),
    ]
