# Generated by Django 2.2 on 2020-04-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_unit_price'),
        ('restaurant', '0004_auto_20200402_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Conta Paga'),
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('table', 'product', 'created_on', 'pay')},
        ),
    ]
